#!/bin/bash

if [[ $1 == "stop" || $1 == "Stop" ]]; then
	systemctl stop ssh
	exit 0
fi

if [[ $1 == "kill" || $1 == "Kill" ]]; then
	pkill ssh
	exit 0
fi

printf "use next args to ex. commands:\n"
printf "\033[1mstop\033[0m - stop ssh\n"
printf "\033[1mkill\033[0m - kill ssh process\n"
